# Generated by Django 4.2.5 on 2023-10-02 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
